"""Initial AgriSync 360 migration

Revision ID: 5a2944e977f9
Revises: 
Create Date: 2026-04-28 20:05:16.165560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '5a2944e977f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(length=50), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('market_name', sa.String(length=120), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'bag_90kg', 'bag_50kg', 'crate', 'bunch', name='market_unit'), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('demand_level', sa.Enum('low', 'medium', 'high', 'very_high', name='market_demand'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_prices_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_crop_name'), ['crop_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_recorded_date'), ['recorded_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'admin', 'ngo_partner', 'agro_dealer', 'county_officer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('weather_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('weather_description', sa.String(length=160), nullable=True),
    sa.Column('disease_risk_level', sa.Enum('low', 'medium', 'high', 'very_high', name='disease_risk'), nullable=False),
    sa.Column('frost_risk', sa.Boolean(), nullable=False),
    sa.Column('planting_window', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_cache_forecast_date'), ['forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_cache_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_cache_longitude'), ['longitude'], unique=False)

    op.create_table('advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.Enum('maize', 'beans', 'potatoes', 'tomatoes', 'tea', 'wheat', 'rice', 'cassava', 'sorghum', 'cabbage', 'kale', 'onions', 'other', name='advisory_crop_name'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('advisory_type', sa.Enum('planting', 'nutrition', 'pest_control', 'irrigation', 'harvest', 'general', 'disease_alert', 'weather_alert', name='advisory_type'), nullable=False),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('season', sa.Enum('long_rains', 'short_rains', 'dry_season', 'all', name='advisory_season'), nullable=False),
    sa.Column('counties_applicable', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisories_advisory_type'), ['advisory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisories_crop_name'), ['crop_name'], unique=False)

    op.create_table('farmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmers_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmers_national_id'), ['national_id'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('weather', 'disease_risk', 'planting_window', 'market_price', 'subscription_expiry', 'general', name='alert_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_via_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('size_acres', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.Enum('clay', 'loam', 'sandy', 'silt', 'peat', name='soil_type'), nullable=False),
    sa.Column('water_source', sa.Enum('rain', 'irrigation', 'river', 'borehole', 'none', name='water_source'), nullable=False),
    sa.Column('elevation_meters', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index('idx_farms_location', ['location'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('ix_farms_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_farms_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('basic_monthly', 'pro_monthly', 'basic_annual', 'pro_annual', 'ngo_annual', 'county_annual', name='subscription_plan'), nullable=False),
    sa.Column('amount_ksh', sa.Float(), nullable=False),
    sa.Column('mpesa_reference', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=120), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=120), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'cancelled', 'refunded', name='payment_status'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_start', sa.Date(), nullable=True),
    sa.Column('subscription_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_reference')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('otp', 'advisory', 'weather_alert', 'market_alert', 'subscription', 'bulk', 'ussd_response', name='sms_message_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', name='sms_status'), nullable=False),
    sa.Column('at_message_id', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_phone_number'), ['phone_number'], unique=False)

    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.Enum('maize', 'beans', 'potatoes', 'tomatoes', 'tea', 'wheat', 'rice', 'cassava', 'sorghum', 'cabbage', 'kale', 'onions', 'other', name='crop_name'), nullable=False),
    sa.Column('variety', sa.String(length=150), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('area_planted_acres', sa.Float(), nullable=False),
    sa.Column('growth_stage', sa.Enum('land_prep', 'planting', 'germination', 'vegetative', 'flowering', 'fruiting', 'maturity', 'harvested', name='growth_stage'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crops_crop_name'), ['crop_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_crops_farm_id'), ['farm_id'], unique=False)

    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crops_farm_id'))
        batch_op.drop_index(batch_op.f('ix_crops_crop_name'))

    op.drop_table('crops')
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_phone_number'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_farmer_id'))

    op.drop_table('sms_logs')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))

    op.drop_table('payments')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_farms_county'))
        batch_op.drop_index('idx_farms_location', postgresql_using='gist')

    op.drop_table('farms')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_farmer_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmers_national_id'))
        batch_op.drop_index(batch_op.f('ix_farmers_county'))

    op.drop_table('farmers')
    with op.batch_alter_table('advisories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisories_crop_name'))
        batch_op.drop_index(batch_op.f('ix_advisories_advisory_type'))

    op.drop_table('advisories')
    with op.batch_alter_table('weather_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_cache_longitude'))
        batch_op.drop_index(batch_op.f('ix_weather_cache_latitude'))
        batch_op.drop_index(batch_op.f('ix_weather_cache_forecast_date'))

    op.drop_table('weather_cache')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_prices_recorded_date'))
        batch_op.drop_index(batch_op.f('ix_market_prices_crop_name'))
        batch_op.drop_index(batch_op.f('ix_market_prices_county'))

    op.drop_table('market_prices')
    # ### end Alembic commands ###
