"""Add otp_type column to users table

Revision ID: b1c2d3e4f5g6
Revises: 5a2944e977f9
Create Date: 2026-05-05 20:46:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5g6'
down_revision = '5a2944e977f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    otp_type_enum = sa.Enum('phone_verification', 'password_reset', name='otp_type_enum')
    otp_type_enum.create(op.get_bind())
    
    # Add the column to the users table
    op.add_column('users', sa.Column('otp_type', otp_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_type')
    
    # Drop the enum type
    otp_type_enum = sa.Enum('phone_verification', 'password_reset', name='otp_type_enum')
    otp_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
